### ISSUE TITLE
icon前台无法全部显示，后台无法配置icon

### ISSUE THREAD

**Issue by disney2002** [ruby-china/homeland-site#1]
可见：https://www.agiledev.cn/sites

后台无法配置每个默认的，使用分析提供的，但是好些无法显示。

但是翻墙后，图标都显示正常。

**Comment by huacnlee** [comment]
这个是正常的，那些图标需要时间才能缓存下来

**Comment by huacnlee** [comment]
暂时无法解决

**Comment by disney2002** [comment]
知道了，thanks，采用了homeland来建站，后面打交道的机会会比较多。
