### ISSUE TITLE
关于不能酷站只能提交http疑问？

### ISSUE THREAD

**Issue by monsterooo** [ruby-china/homeland-site#3]
@huacnlee  华顺哥你好，我看到[这里](https://github.com/ruby-china/homeland-site/blob/master/app/models/site.rb#L21)保存网址的时候过滤掉了https的地址，统一使用了http作为协议。请问这里是作为什么样的考虑呢？ 是否是一个判断失误还是有意这样做的。

**Comment by huacnlee** [comment]
是个 Bug
在 2019年6月28日 +0800 PM5:38，monsterooo <notifications@github.com>，写道：

**Comment by monsterooo** [comment]
> 是个 Bug 在 2019年6月28日 +0800 PM5:38，monsterooo <notifications@github.com>，写道：
> […](#)
> @huacnlee 华顺哥你好，我看到这里保存网址的时候过滤掉了https的地址，统一使用了http作为协议。请问这里是作为什么样的考虑呢？ 是否是一个判断失误还是有意这样做的。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

soga，那就是同时可以支持`http`和`https`协议哈。请问晚上我可以提个PR不

**Comment by huacnlee** [comment]
提吧

monsterooo <notifications@github.com>于2019年6月28日 周五下午5:44写道：

**Comment by monsterooo** [comment]
@huacnlee 华顺我已经提交修复代码，麻烦你检查一下看有啥问题不
